language: generic

install:
  - if [ ! -d ~/cache ] ; then
    mkdir ~/cache ;
    fi
  - if [ ! -d ~/cache/vim -o ! -d ~/cache/vim-themis ] ; then
    git clone https://github.com/thinca/vim-themis ~/cache/vim-themis &&
    git clone https://github.com/vim/vim ~/cache/vim &&
    cd ~/cache/vim &&
    ./configure &&
    make ;
    fi
  - export THEMIS_VIM=~/cache/vim/src/vim

cache:
  directories:
    - $HOME/cache

before_script:
  - ~/cache/vim/src/vim --version

script:
  - cd ~/build/aiya000/vim-ghcid-quickfix
  - ~/cache/vim-themis/bin/themis test/ghcid_quickfix/show_only_error_occured.vimspec --reporter spec
